# Generated by Django 5.0.2 on 2024-05-07 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsApp', '0005_product_main_cat_product_sub_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creater_id', to=settings.AUTH_USER_MODEL)),
                ('interlocutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interlocutor_id', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='productsApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата сообщения')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chatroom_id', to='messageApp.chatroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
