# Generated by Django 5.0.2 on 2024-03-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/avatar.png', null=True, upload_to='avatars'),
        ),
    ]
