# Generated by Django 5.0.2 on 2024-03-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('urlname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('urlname', models.CharField(max_length=20)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productsApp.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('urlname', models.CharField(max_length=20)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productsApp.subcategory')),
            ],
        ),
    ]
