# Generated by Django 5.0.2 on 2024-03-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_alter_detailcategory_name_alter_maincategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
