# Generated by Django 5.0.2 on 2024-03-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_maincategory_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_type', models.BooleanField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('price', models.IntegerField()),
                ('detail_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productsApp.detailcategory', to_field='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
