# Generated by Django 5.0.2 on 2024-03-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_cat',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='productsApp.maincategory', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_cat',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='productsApp.subcategory', to_field='name'),
            preserve_default=False,
        ),
    ]
